### ISSUE TITLE
在maui中一直报错

### ISSUE THREAD

**Issue by ibcla** [jingliancui/AndroidBaiduMapSDKSample#1]
报错信息
![RJV~$@0WE7AS BWLEIO}1T1](https://user-images.githubusercontent.com/43225284/177187586-a88acdb9-ea6a-41eb-910e-f893831f1fff.png)

同样的写法 高德地图可以使用,百度地图不行

在传入Context 的时候就报错

[Sample地址](https://github.com/ibcla/baidumap_Sample)

**Comment by jingliancui** [comment]
已反馈：使用application context即可。
